//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int Id { get; set; }
        public string TextLetter { get; set; }
        public string Subject { get; set; }
        public int IdUserFromWhom { get; set; }
        public int IdUserWhom { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
